<a href="https://colab.research.google.com/github/ai7dnn/2026-1-BDA/blob/main/code/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [4]:
import numpy as np

np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [6]:
np.hstack( (a, c) )

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [5]:
np.column_stack( (a, c) )

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [7]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
np.column_stack( (a, b) )

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])
x

array([[1, 2, 3]])

In [10]:
y

array([[4, 5, 6]])

In [11]:
x.shape, y.shape

((1, 3), (1, 3))

In [12]:
np.column_stack( (x, y) )

array([[1, 2, 3, 4, 5, 6]])

In [14]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [15]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [16]:
np.column_stack( (x, 10, 20, y) )

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [58]:
import numpy as np

rg = np.random.default_rng(1)
rg.random() # [0, 1)

0.5118216247002567

In [66]:
rg.random()

0.5495936876730595

In [68]:
rg.random(5)

array([0.30319483, 0.45349789, 0.1340417 , 0.40311299, 0.20345524])

In [69]:
rg.random( (3, 4) )

array([[0.26231334, 0.75036467, 0.28040876, 0.48519097],
       [0.9807372 , 0.96165719, 0.72478994, 0.54122686],
       [0.2768912 , 0.16065201, 0.96992541, 0.51606859]])

In [70]:
rg.random( (2, 3, 4) )

array([[[0.11586561, 0.62348976, 0.77668311, 0.6130033 ],
        [0.9172977 , 0.03959288, 0.52858926, 0.45933588],
        [0.06234958, 0.64132817, 0.85263284, 0.59294102]],

       [[0.26009745, 0.83988152, 0.50949588, 0.51088888],
        [0.75303021, 0.14792204, 0.81962672, 0.68328691],
        [0.78709694, 0.19161626, 0.80236416, 0.19132393]]])

In [ ]:
rg.random(5)

array([0.30319483, 0.45349789, 0.1340417 , 0.40311299, 0.20345524])

In [ ]:
rg.random(5)

array([0.30319483, 0.45349789, 0.1340417 , 0.40311299, 0.20345524])

In [82]:
import numpy as np

rg = np.random.default_rng(1)
rg.integers(low=0, high=10, size=3) # [0, 10) 정수 난수

array([4, 5, 7])

In [97]:
rg.integers(0, 20, size=(3, 4))

array([[ 1, 15, 16,  9],
       [ 3,  2,  7, 15],
       [ 6,  0, 13, 14]])

In [98]:
rg.integers(1, 7, (3, 4))

array([[2, 4, 3, 4],
       [1, 4, 2, 4],
       [3, 4, 1, 3]])

In [107]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(3) # 표준 정규분포 실수 난수

array([0.34558419, 0.82161814, 0.33043708])

In [144]:
rg.standard_normal((3, 4)) # 표준 정규분포 실수 난수

array([[-0.67247275,  0.58629342,  0.04893524, -1.10360927],
       [-1.12788718, -0.55551921, -0.676006  ,  1.09030239],
       [ 1.3755383 ,  0.86855962,  0.35786889, -0.42823821]])

In [146]:
rg.standard_normal(5)

array([ 0.92333444,  0.87395725, -0.05745005, -2.10423061, -0.78123157])

### 배열 결합 연습

In [149]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [150]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [152]:
np.vstack( (a, b, c) ) # 1D --> 2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
np.vstack( (p, q, r) ) # 2D --> 2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [156]:
np.hstack( (a, b, c) ) # 1D --> 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [157]:
np.hstack( (p, q, r) ) # 2D --> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [159]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [160]:
np.column_stack((a, b, c)) # 1D --> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [161]:
np.column_stack((p, q, r)) # 2D --> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [162]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
np.concatenate((a, b, c), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [165]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
np.concatenate((a, b, c), axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [167]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [168]:
np.concatenate((p, q, r), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [170]:
np.concatenate((p, q, r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [171]:
np.concatenate((p, q, r), axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [172]:
np.concatenate((p, q, r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [173]:
np.c_[a, b, c] # 1D --> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [176]:
np.column_stack( (a, b, c) ) # 1D --> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [177]:
np.column_stack( [a, b, c] )

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [178]:
np.column_stack( a, b, c )

TypeError: column_stack() takes 1 positional argument but 3 were given

In [180]:
np.c_[p, q, r] # 2D --> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [181]:
np.c_[p, q, r] # 2D --> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [183]:
np.r_[a, b, c] # 1D --> 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
np.r_[p, q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [186]:
np.vstack( (p, q, r) )

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])